version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./my-react-app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
